### ISSUE TITLE
Unable to open file languages.rs

### ISSUE THREAD

**Issue by ambi88dex** [SergioBenitez/jellybean#1]
Able to open other files except "languages.rs"

**Comment by ambi88dex** [comment]
![image](https://github.com/SergioBenitez/jellybean/assets/22158125/150724be-c970-4f1b-b32b-b88754c57ed4)

**Comment by SergioBenitez** [comment]
I don't think this has anything to do with the library and looks to be a GitHub issue. In any case, the library isn't quite ready, but it will be very soon.
